version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:8.0-node
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: homestead
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root
      - image: redis:3

    steps:
      - checkout

      - run: sudo apt-get update && sudo apt-get install -y \
          libfreetype6-dev \
          libjpeg62-turbo-dev \
          libpng-dev

      - run: sudo docker-php-ext-configure gd --with-freetype --with-jpeg
      - run: sudo docker-php-ext-install -j$(nproc) gd
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo docker-php-ext-enable pdo_mysql

      - run: chmod -R 777 storage
      - run: cp .env.testing.example .env

      # Download and cache dependencies

      # composer cache
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - composer-v1-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
            - ~/.composer

      # node cache
      - restore_cache:
          keys:
            - node-v4-{{ checksum "package.json" }}
            - node-v4-
      - run: npm install
      - save_cache:
          key: node-v4-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.yarn

      - run: npm run dev

      - run: php artisan migrate --seed
      - run: ./vendor/bin/phpunit

      # run phpunit
      - run: composer test

      - store_test_results:
          path: tests/Report
      - store_artifacts:
          path: tests/Report

      - codecov/upload:
          file: ./tests/Report/clover.xml
